[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vap"
version = "0.1.0"
description = "Video Activity Logger"
authors = [{name="Your Name"}]
requires-python = ">=3.9"
