video_id: vid_demo_cam3
source_camera: cam3
taxonomy_path: configs/taxonomy.yaml
mapping_path: configs/mapping.csv
detect:
  backend: mock
  model_path: null
  classes:
  - person
  - forklift
  - pallet
track:
  backend: bytetrack
  max_age: 30
thresholds:
  pixels_per_meter: 90.0
  fps_target: 30
  speed_drive: 0.2
  speed_stop: 0.05
  debounce_frames: 6
