video_id: vid_demo_cam3
source_camera: cam3
taxonomy_path: configs/taxonomy.yaml
mapping_path: configs/mapping.csv
# roi_mask_path: configs/roi_mask.png   # optional: white area = included region
zones_path: configs/zones.yaml         # optional: zone polygons for zone events
detect:
  backend: yolo
  model_path: best.pt             # default weights (select different ones in the UI drop-down)
  classes: [person, truck, forklift, pallet]               # COCO doesn't include 'truck' or 'pallet' by default
  min_conf: 0.25
  min_box_area: 100
  imgsz: 640
  iou: 0.45
  agnostic_nms: false
  max_det: 1000
  batch_size: 1
  #device: 8                      # set to GPU id or 'cpu'
  # fp16: true
track:
  backend: bytetrack
  max_age: 30
thresholds:
  pixels_per_meter: 90.0
  fps_target: 30
  # truck thresholds (m/s)
  fl_speed_drive: 0.20
  fl_speed_stop: 0.05
  # Human thresholds (m/s)
  hu_speed_walk: 0.50
  hu_speed_wait: 0.08
  # Debounce / durations
  debounce_frames: 6
  min_state_dur_s: 1.0
  merge_gap_s: 0.5
  # Action heuristics
  action_attach_dist_m: 1.0
  action_detach_dist_m: 1.5
  action_attach_frames: 5
  action_detach_frames: 5
