video_id: vid_demo_cam3
source_camera: cam3
taxonomy_path: configs/taxonomy.yaml
mapping_path: configs/mapping.csv
detect:
  backend: yolo
  model_path: yolov8m.pt           # start here; we can fine-tune later
  classes: [person, forklift, pallet]               # COCO doesn't include 'forklift' or 'pallet' by default
track:
  backend: bytetrack
  max_age: 30
thresholds:
  pixels_per_meter: 90.0
  fps_target: 30
  speed_drive: 0.2
  speed_stop: 0.05
  debounce_frames: 6
