zones:
  - name: trailer_area
    polygon:
      - [100, 100]
      - [500, 100]
      - [500, 300]
      - [100, 300]
  - name: stack_area
    polygon:
      - [600, 200]
      - [900, 200]
      - [900, 500]
      - [600, 500]
